<?php

/**
* Implements hook_entity_info_alter().
* With this function you can add extra view modes
*/
function divesitebuddy_custom_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['overview'] = array(
    'label' => t('Overview'),
    'custom settings' => TRUE,
  );
}

/**
* Implements hook_preprocess_node().
*/
function divesitebuddy_custom_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'overview') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__overview';
  }
} 

function divesitebuddy_custom_menu_alter(&$items) {
  $items['user/register']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Add some text to the login form elements description
 */
function divesitebuddy_custom_form_user_login_alter(&$form, &$form_state) {
  dpm('test');
 // $form['name']['#description'] .= ' ' . t('Need an account? Please <a href="!link">register here</a>.', array('!link' => url('user/register')));
  $form['pass']['#description'] = ' ' . t('Forgot your password? <a href="!link">Request a new one</a>!', array('!link' => url('user/password')));
}